[[headers]]
  for = "/*.{js,css,woff2,png,jpg,jpeg,gif,webp,svg,ico}"
    [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.{html,json,xml}"
    [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

# Add this section for SPA routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200