export interface LogEntry {
  timestamp: string;
  code: string;
  userId?: string;
  message: string;
  action?: string;
  metadata?: Record<string, any>;
}

export enum LogCode {
  // Auth Events
  AUTH_SIGNUP_SUCCESS = 'AUTH001',
  AUTH_SIGNUP_FAILED = 'AUTH002',
  AUTH_LOGIN_SUCCESS = 'AUTH003',
  AUTH_LOGIN_FAILED = 'AUTH004',
  AUTH_LOGOUT = 'AUTH005', // Consider renaming to AUTH_LOGOUT_SUCCESS or having separate codes
  AUTH_LOGOUT_SUCCESS = 'AUTH005S', // Added
  AUTH_LOGOUT_FAILED = 'AUTH005F', // Added
  AUTH_PASSWORD_RESET_REQUEST = 'AUTH006',
  AUTH_PASSWORD_RESET_SUCCESS = 'AUTH007',
  AUTH_PASSWORD_RESET_FAILED = 'AUTH008',
  AUTH_PASSWORD_UPDATE_SUCCESS = 'AUTH009', // Added
  AUTH_PASSWORD_UPDATE_FAILED = 'AUTH010', // Added
  AUTH_SESSION_FETCH_FAILED = 'AUTH011', // Added
  AUTH_STATE_CHANGED = 'AUTH012', // Added
  
  // Validation Errors
  VALIDATION_PASSWORD = 'VAL001',
  VALIDATION_EMAIL = 'VAL002',
  
  // Security Events
  SECURITY_ACCOUNT_LOCKED = 'SEC001',
  SECURITY_RATE_LIMIT = 'SEC002',
  SECURITY_SESSION_EXPIRED = 'SEC003',
  
  // Email Verification
  EMAIL_VERIFICATION_SENT = 'EMAIL001',
  EMAIL_VERIFICATION_SUCCESS = 'EMAIL002',
  EMAIL_VERIFICATION_FAILED = 'EMAIL003'
}