#!/usr/bin/env node

const fs = require('node:fs');
const path = require('node:path');

function parseArgs(argv) {
  const args = {};
  for (let i = 2; i < argv.length; i += 1) {
    const token = argv[i];
    if (!token.startsWith('--')) continue;
    const key = token.slice(2);
    const value = argv[i + 1] && !argv[i + 1].startsWith('--') ? argv[i + 1] : 'true';
    args[key] = value;
    if (value !== 'true') i += 1;
  }
  return args;
}

function parseCsvLine(line) {
  const values = [];
  let current = '';
  let inQuotes = false;

  for (let i = 0; i < line.length; i += 1) {
    const char = line[i];

    if (char === '"') {
      if (inQuotes && line[i + 1] === '"') {
        current += '"';
        i += 1;
      } else {
        inQuotes = !inQuotes;
      }
      continue;
    }

    if (char === ',' && !inQuotes) {
      values.push(current);
      current = '';
      continue;
    }

    current += char;
  }

  values.push(current);
  return values;
}

function toUtf8IfMojibake(value) {
  if (!value) return value;
  if (!value.includes('Ã') && !value.includes('Â')) return value;
  try {
    const repaired = Buffer.from(value, 'latin1').toString('utf8');
    return repaired;
  } catch {
    return value;
  }
}

function normalizeName(value) {
  return toUtf8IfMojibake(value)
    .normalize('NFD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/\s+/g, ' ')
    .trim()
    .toLowerCase();
}

function normalizeActivity(value) {
  const fixed = toUtf8IfMojibake(value).replace(/\s+/g, ' ').trim();
  return fixed;
}

function mapDiaSemana(value) {
  const dia = normalizeName(value);
  const map = {
    lunes: 1,
    martes: 2,
    miercoles: 3,
    jueves: 4,
    viernes: 5,
    sabado: 6,
    domingo: 7,
  };
  if (!Object.prototype.hasOwnProperty.call(map, dia)) {
    throw new Error(`Dia no soportado: ${value}`);
  }
  return map[dia];
}

function sqlLiteral(value) {
  return `'${String(value).replace(/'/g, "''")}'`;
}

function classifyLectivo(activity) {
  const value = normalizeName(activity);
  const nonLectiveKeywords = [
    'sin clases',
    'permanencia',
    'almuerzo',
    'reunion',
    'consejo de profesores',
    'depto',
    'volante',
    'pie',
  ];

  return !nonLectiveKeywords.some((keyword) => value.includes(keyword));
}

function main() {
  const args = parseArgs(process.argv);
  const input = args.input || args.i;
  const ownerId = args['owner-id'];
  const output = args.output || args.o || path.join(process.cwd(), 'tmp_horarios_consolidados_import.sql');

  if (!input || !ownerId) {
    console.error('Uso: node scripts/generate_horarios_consolidados_sql.cjs --input <ruta_csv> --owner-id <uuid> [--output <ruta_sql>]');
    process.exit(1);
  }

  const raw = fs.readFileSync(input, 'utf8');
  const lines = raw.split(/\r?\n/).filter((line) => line.trim().length > 0);
  if (lines.length < 2) {
    throw new Error('CSV sin datos.');
  }

  const header = parseCsvLine(lines[0]);
  const expected = ['Profesor', 'Dia', 'Hora_Inicio', 'Hora_Fin', 'Actividad'];
  const valid = expected.every((col, idx) => (header[idx] || '').trim() === col);
  if (!valid) {
    throw new Error(`Header invalido. Esperado: ${expected.join(', ')}`);
  }

  const teacherMap = new Map();
  const scheduleRows = [];

  for (let i = 1; i < lines.length; i += 1) {
    const cols = parseCsvLine(lines[i]);
    if (cols.length < 5) continue;

    const profesor = toUtf8IfMojibake(cols[0]).trim();
    const dia = cols[1].trim();
    const horaInicio = cols[2].trim();
    const horaFin = cols[3].trim();
    const actividad = normalizeActivity(cols.slice(4).join(','));

    if (!profesor || !dia || !horaInicio || !horaFin || !actividad) continue;

    const nombreNormalizado = normalizeName(profesor);
    if (!teacherMap.has(nombreNormalizado)) {
      teacherMap.set(nombreNormalizado, {
        nombre_display: profesor,
        nombre_normalizado: nombreNormalizado,
      });
    }

    scheduleRows.push({
      nombre_normalizado: nombreNormalizado,
      dia_semana: mapDiaSemana(dia),
      hora_inicio: horaInicio,
      hora_fin: horaFin,
      actividad,
      es_lectivo: classifyLectivo(actividad),
    });
  }

  const teachers = [...teacherMap.values()];

  const teacherValuesSql = teachers
    .map((t) => `(${sqlLiteral(ownerId)}::uuid, ${sqlLiteral(t.nombre_display)}, ${sqlLiteral(t.nombre_normalizado)})`)
    .join(',\n    ');

  const scheduleValuesSql = scheduleRows
    .map((row) =>
      `(${sqlLiteral(ownerId)}::uuid, ${sqlLiteral(row.nombre_normalizado)}, ${row.dia_semana}, ${sqlLiteral(row.hora_inicio)}::time, ${sqlLiteral(row.hora_fin)}::time, ${sqlLiteral(row.actividad)}, ${row.es_lectivo ? 'true' : 'false'})`,
    )
    .join(',\n    ');

  const sql = `-- Generated by scripts/generate_horarios_consolidados_sql.cjs\n-- Source: ${input}\n-- Rows: ${scheduleRows.length}\n-- Teachers: ${teachers.length}\n\nBEGIN;\n\nWITH docentes_seed(owner_id, nombre_display, nombre_normalizado) AS (\n  VALUES\n    ${teacherValuesSql}\n)\nINSERT INTO public.docentes (owner_id, nombre_display, nombre_normalizado)\nSELECT owner_id, nombre_display, nombre_normalizado\nFROM docentes_seed\nON CONFLICT (owner_id, nombre_normalizado) DO UPDATE\nSET nombre_display = EXCLUDED.nombre_display,\n    updated_at = now();\n\nWITH horarios_seed(owner_id, nombre_normalizado, dia_semana, hora_inicio, hora_fin, actividad, es_lectivo) AS (\n  VALUES\n    ${scheduleValuesSql}\n), docentes_ref AS (\n  SELECT id, owner_id, nombre_normalizado\n  FROM public.docentes\n  WHERE owner_id = ${sqlLiteral(ownerId)}::uuid\n)\nINSERT INTO public.docentes_horarios_plantilla (\n  owner_id,\n  docente_id,\n  dia_semana,\n  hora_inicio,\n  hora_fin,\n  actividad,\n  es_lectivo\n)\nSELECT\n  hs.owner_id,\n  d.id,
  hs.dia_semana,
  hs.hora_inicio,
  hs.hora_fin,
  hs.actividad,
  hs.es_lectivo
FROM horarios_seed hs
JOIN docentes_ref d
  ON d.owner_id = hs.owner_id
 AND d.nombre_normalizado = hs.nombre_normalizado
ON CONFLICT (owner_id, docente_id, dia_semana, hora_inicio, hora_fin, actividad) DO NOTHING;

COMMIT;
`;

  fs.writeFileSync(output, sql, 'utf8');
  console.log(`SQL generado: ${output}`);
  console.log(`Docentes: ${teachers.length}`);
  console.log(`Bloques horarios: ${scheduleRows.length}`);
}

main();
